### ISSUE TITLE
lag spikeds

### ISSUE THREAD

**Issue by frogglen** [Djaytan/mc-jobs-reborn-patch-place-break#246]
### Observed/problematic behavior

![image](https://github.com/Djaytan/mc-jobs-reborn-patch-place-break/assets/6269642/ddf247b4-358d-4e36-aac9-63642b92088e)

### Expected behavior

I did a spark profiler and it seems that there are some lags with your plugin.

### Steps to reproduce

I did a spark profiler and it seems that there are some lags with your plugin.

**Comment by Djaytan** [comment]
Hello @frogglen,

I see that you are currently relying on SQLite for the data persistence. While in can be a convenient solution for easy and quick setup of the plugin, recommendation is to rely on MySQL/MariaDB instead so that you will observe better performances. 

You can perform the setup in the config file directly.

If you already rely on another SGBD for your server than the ones mentioned, then we can discuss about adding the compatibility for sure.

**Comment by frogglen** [comment]
> Hello @frogglen,
> 
> I see that you are currently relying on SQLite for the data persistence. While in can be a convenient solution for easy and quick setup of the plugin, recommendation is to rely on MySQL/MariaDB instead so that you will observe better performances.
> 
> You can perform the setup in the config file directly.
> 
> If you already rely on another SGBD for your server than the ones mentioned, then we can discuss about adding the compatibility for sure.

I just updated jobs reborn and changed the database to MYSQL with all my data filled correctly, but now when I start the server I get this huge error, I don't know if I did something wrong in the config or if the new version of jobs reborn broke something.

https://mclo.gs/LUkzlZg

**Comment by frogglen** [comment]
sorry i closed for error

**Comment by Djaytan** [comment]
Enjoy the huge stack trace with of the content being useless x)

The error in fact in the following one:
```
Caused by: fr.djaytan.minecraft.jobsreborn.patchplacebreak.lib.com.typesafe.config.ConfigException$Parse: Reader: 32: Expecting close brace } or a comma, got '4' ('+' not followed by =, '4' not allowed after '+') (if you intended '4' ('+' not followed by =, '4' not allowed after '+') to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
```

So simply stated: the configuration file is not properly written (brace or quote missing?)

**Comment by frogglen** [comment]
> Enjoy the huge stack trace with most of the content being useless x)
> 
> The error in fact in the following one:
> 
> ```
> Caused by: fr.djaytan.minecraft.jobsreborn.patchplacebreak.lib.com.typesafe.config.ConfigException$Parse: Reader: 32: Expecting close brace } or a comma, got '4' ('+' not followed by =, '4' not allowed after '+') (if you intended '4' ('+' not followed by =, '4' not allowed after '+') to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
> ```
> 
> So simply stated: the configuration file is not properly written (brace or quote missing?)

i put all my credentials in correctly without """
should I use them?

**Comment by Djaytan** [comment]
If you need information regarding the HOCON syntax: https://github.com/lightbend/config/blob/main/HOCON.md

It is possible to not use double quotes for string values, but this will possible only conditonally: https://github.com/lightbend/config/blob/main/HOCON.md#unquoted-strings

So in short yes surround your value with double quotes, it's safer

**Comment by frogglen** [comment]
> If you need information regarding the HOCON syntax: https://github.com/lightbend/config/blob/main/HOCON.md
> 
> It is possible to not use double quotes for string values, but this will possible only conditonally: https://github.com/lightbend/config/blob/main/HOCON.md#unquoted-strings
> 
> So in short yes surround your value with double quotes, it's safer

https://mclo.gs/34GcCOj

**Comment by Djaytan** [comment]
It seems you are relying on a too old version of MySQL server.
If you want the plugin to work, you will have to bump the database server version.
Flyway which is the solution used under the hood does not support database servers with EOL older than 5 years.
Like you can see by going through [this link](https://endoflife.date/mysql), MySQL 5.7 has reached its end of life. So, consider relying on MySQL 8.0 which is the current LTS.

**Comment by Djaytan** [comment]
Hello @frogglen,
Is your issue resolved?

**Comment by frogglen** [comment]
> Hello @frogglen, Is your issue resolved?

sorry I use this plugin on a shared hosting and they can't change the mysql version, I had to stop using the plugin.

**Comment by Djaytan** [comment]
Hello @frogglen,
FYI I'm working on migrating to Flyway v10 which will reinstall compatibility with old databases... Including MySQL 5.7.
That should unblock you from using the plugin if you are still interested.
I will release a new version once I will have every thing ready.
